### ISSUE TITLE
Value types of `Float` and `Integer`

### ISSUE THREAD

**Issue by jcpunk** [deric/puppet-sysctl_conf#3]
Can the `sysctl_conf::entry` define be extended to also support `Float` and `Integer` values?  That would reduce the frustration when I forget to quote them...

**Comment by deric** [comment]
@jcpunk Is there any kernel parameter that would have a `Float` type? :slightly_smiling_face: 

Some values really needs to be passed as strings:
```
vm.lowmem_reserve_ratio = 256   256     32      0       0
```
Having `Integer` and `String` should be sufficient, don't you think?

**Comment by jcpunk** [comment]
I'm not actually aware of any floats in the wild, but I suspect adding it now would prevent you needing to care in the future?

**Comment by deric** [comment]
Right, but currently the type checking might save us from some typos. When a `Float` is needed we'll tag a new release.

Released as `v0.3.0`.
