### ISSUE TITLE
Update to current dependencies

### ISSUE THREAD

**Issue by jcpunk** [deric/puppet-sysctl_conf#4]
There are new versions of the augeas providers not listed in `metadata.json`

**Comment by deric** [comment]
@jcpunk I was too quick with fixing this. `augeasproviders_sysctl` has latest version [2.6.2](https://forge.puppet.com/modules/herculesteam/augeasproviders_sysctl). It should work just fine.

`herculesteam-augeasproviders_core` has latest version `3.1.0`.
