### ISSUE TITLE
Update dependencies to current

### ISSUE THREAD

**Issue by jcpunk** [deric/puppet-sysctl_conf#7]
The augeasproviders have moved into the voxpupli namespace:

https://forge.puppet.com/modules/puppet/augeasproviders_core/readme
https://forge.puppet.com/modules/puppet/augeasproviders_sysctl/readme

Can this module be updated to use these instead?

**Comment by deric** [comment]
Right, definitely. There was some missing release due to failing tests. Hopefully it's all fixed by now.

**Comment by jcpunk** [comment]
:) may want to list EL9 support while you're there

**Comment by deric** [comment]
Should be resolved in [the latest release](https://github.com/deric/puppet-sysctl_conf/releases/tag/v0.4.0).
